[workspace]
members = [
  "crates/cli",
  "crates/core",
  "crates/executor",
  "crates/pb",
  "crates/rpc",
]
default-members = ["crates/cli"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/hellas-ai/node"
documentation = "https://docs.rs"

[workspace.dependencies]
base64 = "0.22"
blake3 = "1"
catgrad = { git = "https://github.com/georgewhewell/catgrad", branch = "grw/feat/chat-types-on-chatgrad", default-features = false, features = [
  "serde",
] }
catgrad-llm = { git = "https://github.com/georgewhewell/catgrad", branch = "grw/feat/chat-types-on-chatgrad", default-features = false }
catnix = { git = "https://github.com/georgewhewell/catgrad", branch = "grw/feat/chat-types-on-chatgrad", default-features = false }
chatgrad = { git = "https://github.com/georgewhewell/catgrad", branch = "grw/feat/chat-types-on-chatgrad", default-features = false }
half = "2.7.1"
hellas-core = { path = "crates/core", default-features = false }
hellas-executor = { path = "crates/executor", default-features = false }
hellas-pb = { path = "crates/pb", default-features = false }
# tonic-iroh-transport = { path = "../tonic-iroh-transport", default-features = false, features = ["tls-ring", "portmapper", "fast-apple-datapath"] }
# tonic-iroh-transport = { git = "https://github.com/hellas-ai/tonic-iroh-transport", branch = "grw/feat/iroh-0.98", default-features = false, features = ["tls-ring", "portmapper", "fast-apple-datapath"] }

hellas-rpc = { path = "crates/rpc", default-features = false }
hf-hub = { version = "0.5", default-features = false, features = ["ureq"] }
iroh-blobs = { version = "0.100", default-features = false }
k256 = { version = "0.13", features = ["ecdsa"] }
opentelemetry = "0.31"
opentelemetry-otlp = { version = "0.31", default-features = false, features = [
  "http-proto",
  "trace",
  "reqwest-blocking-client",
  "reqwest-rustls-webpki-roots",
] }
opentelemetry_sdk = { version = "0.31", features = ["rt-tokio"] }
reqwest = { version = "0.13", default-features = false, features = [
  "rustls",
  "webpki-roots",
] }
rustls-webpki = "0.103.9"
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
serde_ipld_dagcbor = "=0.6.4"
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = [
  "rt-multi-thread",
  "macros",
  "signal",
  "sync",
  "time",
  "process",
] }
tokio-stream = { version = "0.1", features = ["sync"] }
tonic = { version = "0.14", features = ["gzip"] }
tonic-iroh-transport = { version = "0.9.2", default-features = false, features = [
  "tls-ring",
  "portmapper",
  "fast-apple-datapath",
] }
tracing = "0.1"
tracing-opentelemetry = "0.32"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# [patch."https://github.com/hellas-ai/catgrad"]
# catgrad = { path = "../catgrad/catgrad" }
# catgrad-llm = { path = "../catgrad/catgrad-llm" }

# [patch.crates-io]
# tonic-iroh-transport = { path = "../tonic-iroh-transport" }
