[package]
name = "hellas-pb"
description = "Generated protobuf types for the Hellas protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[features]
default = []
hellas = []
symbolic = ["hellas"]
opaque = ["hellas"]
swarm = []
courtesy = ["hellas", "symbolic"]
settlement = ["hellas"]
client = []
server = []
all = ["hellas", "symbolic", "opaque", "swarm", "courtesy", "client", "server"]
compile = ["dep:glob", "dep:tonic-prost-build", "all"]

[dependencies]
prost = "0.14"
tonic = { version = "0.14", default-features = false, features = ["codegen"] }
tonic-prost = "0.14"

[build-dependencies]
glob = { version = "0.3", optional = true }
tonic-prost-build = { version = "0.14", optional = true }
