[package]
name = "hellas-cli"
description = "Command-line interface for the Hellas node"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[features]
default = ["client"]
client = [
    "hellas-rpc/client",
    "hellas-rpc/discovery",
    "dep:hellas-executor",
    "dep:tonic-iroh-transport",
    "dep:tonic",
    "tonic-iroh-transport/client",
    "tonic-iroh-transport/discovery",
]
serve = ["client", "hellas-rpc/server", "dep:tonic", "tonic-iroh-transport/server"]
cuda = ["client", "hellas-executor/candle-cuda"]
metal = ["client", "hellas-executor/candle-metal"]

[dependencies]
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-opentelemetry.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-otlp.workspace = true
reqwest.workspace = true
catgrad-llm.workspace = true
serde.workspace = true
serde_json.workspace = true

anyhow = "1"
clap = { version = "4", features = ["derive"] }
hellas-rpc = { workspace = true, default-features = false }
hellas-executor = { workspace = true, optional = true }
tonic-iroh-transport = { workspace = true, default-features = false, optional = true }
tonic = { workspace = true, optional = true }
tokio-stream = { workspace = true }
futures = "0.3"
axum = "0.8"
minijinja = "2"
minijinja-contrib = { version = "2", features = ["pycompat"] }

[target.'cfg(target_os = "macos")'.dependencies]
hellas-executor = { workspace = true, optional = true, features = ["candle-metal"] }

# dev-dependencies- add 'compile' feature to hellas-rpc
[dev-dependencies]
# hellas-rpc = { workspace = true, features = ["compile"] }
test-log = { version = "0.2", default-features = false, features = ["trace"] }
