// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetStateRootRequest {}
impl ::prost::Name for GetStateRootRequest {
    const NAME: &'static str = "GetStateRootRequest";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetStateRootRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetStateRootRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetStateRootResponse {
    #[prost(bytes = "vec", optional, tag = "1")]
    pub state_root: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
impl ::prost::Name for GetStateRootResponse {
    const NAME: &'static str = "GetStateRootResponse";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetStateRootResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetStateRootResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetProofRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub object_id: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for GetProofRequest {
    const NAME: &'static str = "GetProofRequest";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetProofRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetProofRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetProofResponse {
    #[prost(bytes = "vec", optional, tag = "1")]
    pub proof: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
impl ::prost::Name for GetProofResponse {
    const NAME: &'static str = "GetProofResponse";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetProofResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetProofResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCoinRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub object_id: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for GetCoinRequest {
    const NAME: &'static str = "GetCoinRequest";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetCoinRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetCoinRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCoinResponse {
    #[prost(bytes = "vec", optional, tag = "1")]
    pub owner: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, optional, tag = "2")]
    pub value: ::core::option::Option<u64>,
}
impl ::prost::Name for GetCoinResponse {
    const NAME: &'static str = "GetCoinResponse";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetCoinResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetCoinResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetFinalizationRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for GetFinalizationRequest {
    const NAME: &'static str = "GetFinalizationRequest";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetFinalizationRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetFinalizationRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetFinalizationResponse {
    #[prost(bytes = "vec", optional, tag = "1")]
    pub certificate: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
impl ::prost::Name for GetFinalizationResponse {
    const NAME: &'static str = "GetFinalizationResponse";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetFinalizationResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetFinalizationResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FinalizedSnapshot {
    #[prost(uint64, tag = "1")]
    pub height: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub state_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub finalization: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for FinalizedSnapshot {
    const NAME: &'static str = "FinalizedSnapshot";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.FinalizedSnapshot".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.FinalizedSnapshot".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetLatestBlockRequest {}
impl ::prost::Name for GetLatestBlockRequest {
    const NAME: &'static str = "GetLatestBlockRequest";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetLatestBlockRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetLatestBlockRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetLatestBlockResponse {
    #[prost(message, optional, tag = "1")]
    pub latest: ::core::option::Option<FinalizedSnapshot>,
}
impl ::prost::Name for GetLatestBlockResponse {
    const NAME: &'static str = "GetLatestBlockResponse";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetLatestBlockResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetLatestBlockResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubmitTxRequest {
    #[prost(oneof = "submit_tx_request::Tx", tags = "1, 2")]
    pub tx: ::core::option::Option<submit_tx_request::Tx>,
}
/// Nested message and enum types in `SubmitTxRequest`.
pub mod submit_tx_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Tx {
        #[prost(message, tag = "1")]
        Transfer(super::TransferTx),
        #[prost(message, tag = "2")]
        MergeCoin(super::MergeCoinTx),
    }
}
impl ::prost::Name for SubmitTxRequest {
    const NAME: &'static str = "SubmitTxRequest";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.SubmitTxRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.SubmitTxRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WebAuthnSignature {
    /// ASN.1 DER-encoded ECDSA(P-256) signature from WebAuthn assertion response.
    #[prost(bytes = "vec", tag = "1")]
    pub ecdsa_signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub authenticator_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub client_data_json: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for WebAuthnSignature {
    const NAME: &'static str = "WebAuthnSignature";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.WebAuthnSignature".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.WebAuthnSignature".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TransferTx {
    #[prost(bytes = "vec", tag = "1")]
    pub input: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub recipient: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "3")]
    pub amount: u64,
    #[prost(message, optional, tag = "4")]
    pub signature: ::core::option::Option<WebAuthnSignature>,
}
impl ::prost::Name for TransferTx {
    const NAME: &'static str = "TransferTx";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.TransferTx".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.TransferTx".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MergeCoinTx {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub inputs: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, optional, tag = "2")]
    pub signature: ::core::option::Option<WebAuthnSignature>,
}
impl ::prost::Name for MergeCoinTx {
    const NAME: &'static str = "MergeCoinTx";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.MergeCoinTx".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.MergeCoinTx".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubmitTxResponse {}
impl ::prost::Name for SubmitTxResponse {
    const NAME: &'static str = "SubmitTxResponse";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.SubmitTxResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.SubmitTxResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubscribeActivityRequest {
    /// Event kinds the relay should deliver immediately. Anything not listed may
    /// be batched by the relay (flushed on a short timer or when its buffer fills).
    /// Empty (default): every event is urgent.
    #[prost(enumeration = "ActivityEventKind", repeated, tag = "1")]
    pub urgent_events: ::prost::alloc::vec::Vec<i32>,
}
impl ::prost::Name for SubscribeActivityRequest {
    const NAME: &'static str = "SubscribeActivityRequest";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.SubscribeActivityRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.SubscribeActivityRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetValidatorsRequest {}
impl ::prost::Name for GetValidatorsRequest {
    const NAME: &'static str = "GetValidatorsRequest";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetValidatorsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetValidatorsRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetValidatorsResponse {
    #[prost(string, repeated, tag = "1")]
    pub validators: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
impl ::prost::Name for GetValidatorsResponse {
    const NAME: &'static str = "GetValidatorsResponse";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetValidatorsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetValidatorsResponse".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetConsensusInfoRequest {}
impl ::prost::Name for GetConsensusInfoRequest {
    const NAME: &'static str = "GetConsensusInfoRequest";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetConsensusInfoRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetConsensusInfoRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetConsensusInfoResponse {
    #[prost(string, repeated, tag = "1")]
    pub validators: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bytes = "vec", tag = "2")]
    pub threshold_identity: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for GetConsensusInfoResponse {
    const NAME: &'static str = "GetConsensusInfoResponse";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetConsensusInfoResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetConsensusInfoResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCoinsByOwnerRequest {
    /// 33-byte compressed secp256r1 public key
    #[prost(bytes = "vec", tag = "1")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for GetCoinsByOwnerRequest {
    const NAME: &'static str = "GetCoinsByOwnerRequest";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetCoinsByOwnerRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetCoinsByOwnerRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CoinEntry {
    /// 32-byte ObjectId
    #[prost(bytes = "vec", tag = "1")]
    pub object_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub value: u64,
}
impl ::prost::Name for CoinEntry {
    const NAME: &'static str = "CoinEntry";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.CoinEntry".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.CoinEntry".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCoinsByOwnerResponse {
    #[prost(message, optional, tag = "1")]
    pub snapshot: ::core::option::Option<FinalizedSnapshot>,
    #[prost(message, repeated, tag = "2")]
    pub coins: ::prost::alloc::vec::Vec<CoinEntry>,
}
impl ::prost::Name for GetCoinsByOwnerResponse {
    const NAME: &'static str = "GetCoinsByOwnerResponse";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetCoinsByOwnerResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetCoinsByOwnerResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProposalInfo {
    #[prost(uint64, tag = "1")]
    pub epoch: u64,
    #[prost(uint64, tag = "2")]
    pub view: u64,
    #[prost(uint64, tag = "3")]
    pub parent_view: u64,
    #[prost(bytes = "vec", tag = "4")]
    pub parent_payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for ProposalInfo {
    const NAME: &'static str = "ProposalInfo";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.ProposalInfo".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.ProposalInfo".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NotarizeEvent {
    #[prost(message, optional, tag = "1")]
    pub proposal: ::core::option::Option<ProposalInfo>,
    #[prost(uint32, tag = "2")]
    pub signer: u32,
    #[prost(bytes = "vec", tag = "3")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for NotarizeEvent {
    const NAME: &'static str = "NotarizeEvent";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.NotarizeEvent".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.NotarizeEvent".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NotarizationEvent {
    #[prost(message, optional, tag = "1")]
    pub proposal: ::core::option::Option<ProposalInfo>,
    #[prost(uint32, repeated, tag = "2")]
    pub signers: ::prost::alloc::vec::Vec<u32>,
    #[prost(bytes = "vec", tag = "3")]
    pub certificate: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for NotarizationEvent {
    const NAME: &'static str = "NotarizationEvent";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.NotarizationEvent".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.NotarizationEvent".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NullifyEvent {
    #[prost(uint64, tag = "1")]
    pub epoch: u64,
    #[prost(uint64, tag = "2")]
    pub view: u64,
    #[prost(uint32, tag = "3")]
    pub signer: u32,
    #[prost(bytes = "vec", tag = "4")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for NullifyEvent {
    const NAME: &'static str = "NullifyEvent";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.NullifyEvent".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.NullifyEvent".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NullificationEvent {
    #[prost(uint64, tag = "1")]
    pub epoch: u64,
    #[prost(uint64, tag = "2")]
    pub view: u64,
    #[prost(uint32, repeated, tag = "3")]
    pub signers: ::prost::alloc::vec::Vec<u32>,
    #[prost(bytes = "vec", tag = "4")]
    pub certificate: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for NullificationEvent {
    const NAME: &'static str = "NullificationEvent";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.NullificationEvent".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.NullificationEvent".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FinalizationEvent {
    #[prost(message, optional, tag = "1")]
    pub proposal: ::core::option::Option<ProposalInfo>,
    #[prost(uint32, repeated, tag = "2")]
    pub signers: ::prost::alloc::vec::Vec<u32>,
    #[prost(bytes = "vec", tag = "3")]
    pub certificate: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for FinalizationEvent {
    const NAME: &'static str = "FinalizationEvent";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.FinalizationEvent".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.FinalizationEvent".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetRelayInfoRequest {}
impl ::prost::Name for GetRelayInfoRequest {
    const NAME: &'static str = "GetRelayInfoRequest";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetRelayInfoRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetRelayInfoRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetRelayInfoResponse {
    #[prost(string, tag = "1")]
    pub relay_version: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub relay_rev: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub node_rpc_version: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub node_rpc_rev: ::prost::alloc::string::String,
}
impl ::prost::Name for GetRelayInfoResponse {
    const NAME: &'static str = "GetRelayInfoResponse";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetRelayInfoResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetRelayInfoResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActivityEvent {
    /// Relay hop timestamps in unix milliseconds.
    /// \[0\] validator emit time, \[1\] durable-object relay receive time.
    #[prost(uint64, repeated, tag = "7")]
    pub relay_timestamps: ::prost::alloc::vec::Vec<u64>,
    /// Cloudflare edge colo code (e.g. "FRA"), injected by the relay.
    #[prost(string, tag = "8")]
    pub edge_colo: ::prost::alloc::string::String,
    #[prost(oneof = "activity_event::Event", tags = "1, 2, 3, 4, 5")]
    pub event: ::core::option::Option<activity_event::Event>,
}
/// Nested message and enum types in `ActivityEvent`.
pub mod activity_event {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "1")]
        Notarize(super::NotarizeEvent),
        #[prost(message, tag = "2")]
        Notarization(super::NotarizationEvent),
        #[prost(message, tag = "3")]
        Nullify(super::NullifyEvent),
        #[prost(message, tag = "4")]
        Nullification(super::NullificationEvent),
        #[prost(message, tag = "5")]
        Finalization(super::FinalizationEvent),
    }
}
impl ::prost::Name for ActivityEvent {
    const NAME: &'static str = "ActivityEvent";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.ActivityEvent".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.ActivityEvent".into()
    }
}
/// Identifies the variant of `ActivityEvent.event`. Numbering matches the
/// oneof tags so callers can map field numbers \<-> enum values directly.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ActivityEventKind {
    Unknown = 0,
    Notarize = 1,
    Notarization = 2,
    Nullify = 3,
    Nullification = 4,
    Finalization = 5,
}
impl ActivityEventKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "ACTIVITY_EVENT_KIND_UNKNOWN",
            Self::Notarize => "ACTIVITY_EVENT_KIND_NOTARIZE",
            Self::Notarization => "ACTIVITY_EVENT_KIND_NOTARIZATION",
            Self::Nullify => "ACTIVITY_EVENT_KIND_NULLIFY",
            Self::Nullification => "ACTIVITY_EVENT_KIND_NULLIFICATION",
            Self::Finalization => "ACTIVITY_EVENT_KIND_FINALIZATION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ACTIVITY_EVENT_KIND_UNKNOWN" => Some(Self::Unknown),
            "ACTIVITY_EVENT_KIND_NOTARIZE" => Some(Self::Notarize),
            "ACTIVITY_EVENT_KIND_NOTARIZATION" => Some(Self::Notarization),
            "ACTIVITY_EVENT_KIND_NULLIFY" => Some(Self::Nullify),
            "ACTIVITY_EVENT_KIND_NULLIFICATION" => Some(Self::Nullification),
            "ACTIVITY_EVENT_KIND_FINALIZATION" => Some(Self::Finalization),
            _ => None,
        }
    }
}
/// Generated client implementations.
#[cfg(feature = "client")]
pub mod light_client_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct LightClientClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl<T> LightClientClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> LightClientClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            LightClientClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get_state_root(
            &mut self,
            request: impl tonic::IntoRequest<super::GetStateRootRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStateRootResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.LightClient/GetStateRoot",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.LightClient", "GetStateRoot"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_proof(
            &mut self,
            request: impl tonic::IntoRequest<super::GetProofRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetProofResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.LightClient/GetProof",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.LightClient", "GetProof"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_coin(
            &mut self,
            request: impl tonic::IntoRequest<super::GetCoinRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetCoinResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.LightClient/GetCoin",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.LightClient", "GetCoin"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_finalization(
            &mut self,
            request: impl tonic::IntoRequest<super::GetFinalizationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetFinalizationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.LightClient/GetFinalization",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.LightClient", "GetFinalization"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_latest_block(
            &mut self,
            request: impl tonic::IntoRequest<super::GetLatestBlockRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetLatestBlockResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.LightClient/GetLatestBlock",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.LightClient", "GetLatestBlock"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn submit_tx(
            &mut self,
            request: impl tonic::IntoRequest<super::SubmitTxRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SubmitTxResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.LightClient/SubmitTx",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.LightClient", "SubmitTx"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn subscribe_activity(
            &mut self,
            request: impl tonic::IntoRequest<super::SubscribeActivityRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ActivityEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.LightClient/SubscribeActivity",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.LightClient", "SubscribeActivity"));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn get_validators(
            &mut self,
            request: impl tonic::IntoRequest<super::GetValidatorsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetValidatorsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.LightClient/GetValidators",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.LightClient", "GetValidators"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_coins_by_owner(
            &mut self,
            request: impl tonic::IntoRequest<super::GetCoinsByOwnerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetCoinsByOwnerResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.LightClient/GetCoinsByOwner",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.LightClient", "GetCoinsByOwner"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_relay_info(
            &mut self,
            request: impl tonic::IntoRequest<super::GetRelayInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetRelayInfoResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.LightClient/GetRelayInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.LightClient", "GetRelayInfo"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_consensus_info(
            &mut self,
            request: impl tonic::IntoRequest<super::GetConsensusInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetConsensusInfoResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.LightClient/GetConsensusInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.LightClient", "GetConsensusInfo"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
#[cfg(feature = "server")]
pub mod light_client_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with LightClientServer.
    #[async_trait]
    pub trait LightClient: std::marker::Send + std::marker::Sync + 'static {
        async fn get_state_root(
            &self,
            request: tonic::Request<super::GetStateRootRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStateRootResponse>,
            tonic::Status,
        >;
        async fn get_proof(
            &self,
            request: tonic::Request<super::GetProofRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetProofResponse>,
            tonic::Status,
        >;
        async fn get_coin(
            &self,
            request: tonic::Request<super::GetCoinRequest>,
        ) -> std::result::Result<tonic::Response<super::GetCoinResponse>, tonic::Status>;
        async fn get_finalization(
            &self,
            request: tonic::Request<super::GetFinalizationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetFinalizationResponse>,
            tonic::Status,
        >;
        async fn get_latest_block(
            &self,
            request: tonic::Request<super::GetLatestBlockRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetLatestBlockResponse>,
            tonic::Status,
        >;
        async fn submit_tx(
            &self,
            request: tonic::Request<super::SubmitTxRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SubmitTxResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the SubscribeActivity method.
        type SubscribeActivityStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ActivityEvent, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn subscribe_activity(
            &self,
            request: tonic::Request<super::SubscribeActivityRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::SubscribeActivityStream>,
            tonic::Status,
        >;
        async fn get_validators(
            &self,
            request: tonic::Request<super::GetValidatorsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetValidatorsResponse>,
            tonic::Status,
        >;
        async fn get_coins_by_owner(
            &self,
            request: tonic::Request<super::GetCoinsByOwnerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetCoinsByOwnerResponse>,
            tonic::Status,
        >;
        async fn get_relay_info(
            &self,
            request: tonic::Request<super::GetRelayInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetRelayInfoResponse>,
            tonic::Status,
        >;
        async fn get_consensus_info(
            &self,
            request: tonic::Request<super::GetConsensusInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetConsensusInfoResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct LightClientServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> LightClientServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for LightClientServer<T>
    where
        T: LightClient,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/hellas.LightClient/GetStateRoot" => {
                    #[allow(non_camel_case_types)]
                    struct GetStateRootSvc<T: LightClient>(pub Arc<T>);
                    impl<
                        T: LightClient,
                    > tonic::server::UnaryService<super::GetStateRootRequest>
                    for GetStateRootSvc<T> {
                        type Response = super::GetStateRootResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetStateRootRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LightClient>::get_state_root(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetStateRootSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.LightClient/GetProof" => {
                    #[allow(non_camel_case_types)]
                    struct GetProofSvc<T: LightClient>(pub Arc<T>);
                    impl<
                        T: LightClient,
                    > tonic::server::UnaryService<super::GetProofRequest>
                    for GetProofSvc<T> {
                        type Response = super::GetProofResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetProofRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LightClient>::get_proof(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetProofSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.LightClient/GetCoin" => {
                    #[allow(non_camel_case_types)]
                    struct GetCoinSvc<T: LightClient>(pub Arc<T>);
                    impl<
                        T: LightClient,
                    > tonic::server::UnaryService<super::GetCoinRequest>
                    for GetCoinSvc<T> {
                        type Response = super::GetCoinResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetCoinRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LightClient>::get_coin(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetCoinSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.LightClient/GetFinalization" => {
                    #[allow(non_camel_case_types)]
                    struct GetFinalizationSvc<T: LightClient>(pub Arc<T>);
                    impl<
                        T: LightClient,
                    > tonic::server::UnaryService<super::GetFinalizationRequest>
                    for GetFinalizationSvc<T> {
                        type Response = super::GetFinalizationResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetFinalizationRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LightClient>::get_finalization(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetFinalizationSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.LightClient/GetLatestBlock" => {
                    #[allow(non_camel_case_types)]
                    struct GetLatestBlockSvc<T: LightClient>(pub Arc<T>);
                    impl<
                        T: LightClient,
                    > tonic::server::UnaryService<super::GetLatestBlockRequest>
                    for GetLatestBlockSvc<T> {
                        type Response = super::GetLatestBlockResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetLatestBlockRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LightClient>::get_latest_block(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetLatestBlockSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.LightClient/SubmitTx" => {
                    #[allow(non_camel_case_types)]
                    struct SubmitTxSvc<T: LightClient>(pub Arc<T>);
                    impl<
                        T: LightClient,
                    > tonic::server::UnaryService<super::SubmitTxRequest>
                    for SubmitTxSvc<T> {
                        type Response = super::SubmitTxResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SubmitTxRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LightClient>::submit_tx(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SubmitTxSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.LightClient/SubscribeActivity" => {
                    #[allow(non_camel_case_types)]
                    struct SubscribeActivitySvc<T: LightClient>(pub Arc<T>);
                    impl<
                        T: LightClient,
                    > tonic::server::ServerStreamingService<
                        super::SubscribeActivityRequest,
                    > for SubscribeActivitySvc<T> {
                        type Response = super::ActivityEvent;
                        type ResponseStream = T::SubscribeActivityStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SubscribeActivityRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LightClient>::subscribe_activity(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SubscribeActivitySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.LightClient/GetValidators" => {
                    #[allow(non_camel_case_types)]
                    struct GetValidatorsSvc<T: LightClient>(pub Arc<T>);
                    impl<
                        T: LightClient,
                    > tonic::server::UnaryService<super::GetValidatorsRequest>
                    for GetValidatorsSvc<T> {
                        type Response = super::GetValidatorsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetValidatorsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LightClient>::get_validators(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetValidatorsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.LightClient/GetCoinsByOwner" => {
                    #[allow(non_camel_case_types)]
                    struct GetCoinsByOwnerSvc<T: LightClient>(pub Arc<T>);
                    impl<
                        T: LightClient,
                    > tonic::server::UnaryService<super::GetCoinsByOwnerRequest>
                    for GetCoinsByOwnerSvc<T> {
                        type Response = super::GetCoinsByOwnerResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetCoinsByOwnerRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LightClient>::get_coins_by_owner(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetCoinsByOwnerSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.LightClient/GetRelayInfo" => {
                    #[allow(non_camel_case_types)]
                    struct GetRelayInfoSvc<T: LightClient>(pub Arc<T>);
                    impl<
                        T: LightClient,
                    > tonic::server::UnaryService<super::GetRelayInfoRequest>
                    for GetRelayInfoSvc<T> {
                        type Response = super::GetRelayInfoResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetRelayInfoRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LightClient>::get_relay_info(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetRelayInfoSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.LightClient/GetConsensusInfo" => {
                    #[allow(non_camel_case_types)]
                    struct GetConsensusInfoSvc<T: LightClient>(pub Arc<T>);
                    impl<
                        T: LightClient,
                    > tonic::server::UnaryService<super::GetConsensusInfoRequest>
                    for GetConsensusInfoSvc<T> {
                        type Response = super::GetConsensusInfoResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetConsensusInfoRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LightClient>::get_consensus_info(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetConsensusInfoSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for LightClientServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "hellas.LightClient";
    impl<T> tonic::server::NamedService for LightClientServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
