// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SymbolicStart {
    #[prost(oneof = "symbolic_start::Kind", tags = "1, 2")]
    pub kind: ::core::option::Option<symbolic_start::Kind>,
}
/// Nested message and enum types in `SymbolicStart`.
pub mod symbolic_start {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        Genesis(super::SymbolicGenesisStart),
        #[prost(message, tag = "2")]
        Artifact(super::SymbolicArtifactStart),
    }
}
impl ::prost::Name for SymbolicStart {
    const NAME: &'static str = "SymbolicStart";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.SymbolicStart".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.SymbolicStart".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SymbolicGenesisStart {}
impl ::prost::Name for SymbolicGenesisStart {
    const NAME: &'static str = "SymbolicGenesisStart";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.SymbolicGenesisStart".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.SymbolicGenesisStart".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SymbolicArtifactStart {
    /// catnix OutputId<TextArtifact>; exactly 32 bytes.
    #[prost(bytes = "vec", tag = "1")]
    pub artifact_cid: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for SymbolicArtifactStart {
    const NAME: &'static str = "SymbolicArtifactStart";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.SymbolicArtifactStart".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.SymbolicArtifactStart".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuotePreparedTextRequest {
    #[prost(string, tag = "1")]
    pub huggingface_model_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub huggingface_revision: ::prost::alloc::string::String,
    #[prost(uint32, repeated, tag = "3")]
    pub prompt_token_ids: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, tag = "4")]
    pub max_new_tokens: u32,
    #[prost(uint32, repeated, tag = "5")]
    pub stop_token_ids: ::prost::alloc::vec::Vec<u32>,
    #[prost(message, optional, tag = "6")]
    pub start: ::core::option::Option<SymbolicStart>,
    /// Ordered preference list (each one of "f32", "f16", "bf16"). The server
    /// picks the first entry it supports. Empty list lets the server pick its
    /// preferred dtype freely. None of the entries supported -> request is
    /// refused with FailedPrecondition. The chosen dtype is reported back in
    /// QuotePreparedTextResponse.dtype.
    #[prost(string, repeated, tag = "7")]
    pub accept_dtypes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
impl ::prost::Name for QuotePreparedTextRequest {
    const NAME: &'static str = "QuotePreparedTextRequest";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.QuotePreparedTextRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.QuotePreparedTextRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuotePreparedTextResponse {
    #[prost(message, optional, tag = "1")]
    pub ticket: ::core::option::Option<super::super::v1::Ticket>,
    #[prost(uint32, tag = "2")]
    pub prompt_tokens: u32,
    /// The dtype the server actually committed to running this quote at.
    #[prost(string, tag = "3")]
    pub dtype: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub symbolic_request: ::core::option::Option<
        super::super::symbolic::v1::SymbolicRequest,
    >,
}
impl ::prost::Name for QuotePreparedTextResponse {
    const NAME: &'static str = "QuotePreparedTextResponse";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.QuotePreparedTextResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.QuotePreparedTextResponse".into()
    }
}
/// Convenience RPC: the server handles tokenization and symbolic request
/// construction. Intended for lightweight clients (browsers) that don't have
/// the tokenizer.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuotePromptRequest {
    #[prost(string, tag = "1")]
    pub huggingface_model_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub huggingface_revision: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub prompt: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub max_new_tokens: u32,
    /// Ordered preference list (each one of "f32", "f16", "bf16"). The server
    /// picks the first entry it supports. Empty list lets the server pick its
    /// preferred dtype freely. None of the entries supported -> request is
    /// refused with FailedPrecondition. The chosen dtype is reported back in
    /// QuotePromptResponse.dtype.
    #[prost(string, repeated, tag = "5")]
    pub accept_dtypes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
impl ::prost::Name for QuotePromptRequest {
    const NAME: &'static str = "QuotePromptRequest";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.QuotePromptRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.QuotePromptRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuotePromptResponse {
    #[prost(message, optional, tag = "1")]
    pub ticket: ::core::option::Option<super::super::v1::Ticket>,
    #[prost(uint32, tag = "2")]
    pub prompt_tokens: u32,
    /// The dtype the server actually committed to running this quote at.
    #[prost(string, tag = "3")]
    pub dtype: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub symbolic_request: ::core::option::Option<
        super::super::symbolic::v1::SymbolicRequest,
    >,
}
impl ::prost::Name for QuotePromptResponse {
    const NAME: &'static str = "QuotePromptResponse";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.QuotePromptResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.QuotePromptResponse".into()
    }
}
/// Convenience RPC: chat-style prompt quoting.
/// Like QuotePrompt but accepts a message array + system prompt.
/// The server applies the model's chat template to produce the prompt.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChatMessage {
    /// "user", "assistant"
    #[prost(string, tag = "1")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
}
impl ::prost::Name for ChatMessage {
    const NAME: &'static str = "ChatMessage";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.ChatMessage".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.ChatMessage".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QuoteChatPromptRequest {
    #[prost(string, tag = "1")]
    pub huggingface_model_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub huggingface_revision: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub messages: ::prost::alloc::vec::Vec<ChatMessage>,
    #[prost(uint32, tag = "4")]
    pub max_new_tokens: u32,
    #[prost(string, tag = "5")]
    pub system_prompt: ::prost::alloc::string::String,
    /// Ordered preference list (each one of "f32", "f16", "bf16"). The server
    /// picks the first entry it supports. Empty list lets the server pick its
    /// preferred dtype freely. None of the entries supported -> request is
    /// refused with FailedPrecondition. The chosen dtype is reported back in
    /// QuoteChatPromptResponse.dtype.
    #[prost(string, repeated, tag = "6")]
    pub accept_dtypes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
impl ::prost::Name for QuoteChatPromptRequest {
    const NAME: &'static str = "QuoteChatPromptRequest";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.QuoteChatPromptRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.QuoteChatPromptRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuoteChatPromptResponse {
    #[prost(message, optional, tag = "1")]
    pub ticket: ::core::option::Option<super::super::v1::Ticket>,
    #[prost(uint32, tag = "2")]
    pub prompt_tokens: u32,
    /// The dtype the server actually committed to running this quote at.
    #[prost(string, tag = "3")]
    pub dtype: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub symbolic_request: ::core::option::Option<
        super::super::symbolic::v1::SymbolicRequest,
    >,
}
impl ::prost::Name for QuoteChatPromptResponse {
    const NAME: &'static str = "QuoteChatPromptResponse";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.QuoteChatPromptResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.QuoteChatPromptResponse".into()
    }
}
/// Store one canonical catnix artifact by its BLAKE3 CID. This API does not
/// publish symbolic metadata such as model locators or lazy substitutions; those
/// are separate provider-local interpretation state.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PutArtifactRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub canonical_artifact: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for PutArtifactRequest {
    const NAME: &'static str = "PutArtifactRequest";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.PutArtifactRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.PutArtifactRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PutArtifactResponse {
    /// BLAKE3 digest of canonical_artifact; exactly 32 bytes.
    #[prost(bytes = "vec", tag = "1")]
    pub cid: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for PutArtifactResponse {
    const NAME: &'static str = "PutArtifactResponse";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.PutArtifactResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.PutArtifactResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetArtifactRequest {
    /// BLAKE3 digest of canonical artifact bytes; exactly 32 bytes.
    #[prost(bytes = "vec", tag = "1")]
    pub cid: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for GetArtifactRequest {
    const NAME: &'static str = "GetArtifactRequest";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.GetArtifactRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.GetArtifactRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetArtifactResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub canonical_artifact: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for GetArtifactResponse {
    const NAME: &'static str = "GetArtifactResponse";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.GetArtifactResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.GetArtifactResponse".into()
    }
}
/// List models known to the executor and their readiness status.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListModelsRequest {}
impl ::prost::Name for ListModelsRequest {
    const NAME: &'static str = "ListModelsRequest";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.ListModelsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.ListModelsRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModelInfo {
    #[prost(string, tag = "1")]
    pub model_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub revision: ::prost::alloc::string::String,
    #[prost(enumeration = "ModelStatus", tag = "3")]
    pub status: i32,
    /// Human-readable error when status is FAILED.
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
}
impl ::prost::Name for ModelInfo {
    const NAME: &'static str = "ModelInfo";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.ModelInfo".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.ModelInfo".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListModelsResponse {
    #[prost(message, repeated, tag = "1")]
    pub models: ::prost::alloc::vec::Vec<ModelInfo>,
}
impl ::prost::Name for ListModelsResponse {
    const NAME: &'static str = "ListModelsResponse";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.ListModelsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.ListModelsResponse".into()
    }
}
/// Convenience RPC: stateless token decoding.
/// Client streams raw token bytes, server decodes with the model's tokenizer
/// and streams back text chunks.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DecodeTokensRequest {
    #[prost(string, tag = "1")]
    pub huggingface_model_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub huggingface_revision: ::prost::alloc::string::String,
    /// Raw token bytes (little-endian u32 token IDs, same format as Symbolic output).
    #[prost(bytes = "vec", tag = "3")]
    pub token_bytes: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for DecodeTokensRequest {
    const NAME: &'static str = "DecodeTokensRequest";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.DecodeTokensRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.DecodeTokensRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DecodeTokensResponse {
    /// Decoded text (incremental delta; concatenate all responses for full output).
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
}
impl ::prost::Name for DecodeTokensResponse {
    const NAME: &'static str = "DecodeTokensResponse";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.DecodeTokensResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.DecodeTokensResponse".into()
    }
}
/// Cumulative token statistics since node start.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetStatsRequest {}
impl ::prost::Name for GetStatsRequest {
    const NAME: &'static str = "GetStatsRequest";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.GetStatsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.GetStatsRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TokenStats {
    #[prost(uint64, tag = "1")]
    pub executions_started: u64,
    #[prost(uint64, tag = "2")]
    pub executions_completed: u64,
    #[prost(uint64, tag = "3")]
    pub executions_failed: u64,
    #[prost(uint64, tag = "4")]
    pub prompt_tokens: u64,
    #[prost(uint64, tag = "5")]
    pub cached_prompt_tokens: u64,
    #[prost(uint64, tag = "6")]
    pub cached_output_tokens: u64,
    #[prost(uint64, tag = "7")]
    pub prefill_tokens: u64,
    #[prost(uint64, tag = "8")]
    pub generated_tokens: u64,
}
impl ::prost::Name for TokenStats {
    const NAME: &'static str = "TokenStats";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.TokenStats".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.TokenStats".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModelTokenStats {
    #[prost(string, tag = "1")]
    pub model_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub stats: ::core::option::Option<TokenStats>,
}
impl ::prost::Name for ModelTokenStats {
    const NAME: &'static str = "ModelTokenStats";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.ModelTokenStats".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.ModelTokenStats".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetStatsResponse {
    #[prost(message, optional, tag = "1")]
    pub stats: ::core::option::Option<TokenStats>,
    #[prost(message, repeated, tag = "2")]
    pub model_stats: ::prost::alloc::vec::Vec<ModelTokenStats>,
}
impl ::prost::Name for GetStatsResponse {
    const NAME: &'static str = "GetStatsResponse";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.GetStatsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.GetStatsResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetModelStatsRequest {
    #[prost(string, tag = "1")]
    pub model_id: ::prost::alloc::string::String,
}
impl ::prost::Name for GetModelStatsRequest {
    const NAME: &'static str = "GetModelStatsRequest";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.GetModelStatsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.GetModelStatsRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetModelStatsResponse {
    #[prost(string, tag = "1")]
    pub model_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub stats: ::core::option::Option<TokenStats>,
}
impl ::prost::Name for GetModelStatsResponse {
    const NAME: &'static str = "GetModelStatsResponse";
    const PACKAGE: &'static str = "hellas.courtesy.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.courtesy.v1.GetModelStatsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.courtesy.v1.GetModelStatsResponse".into()
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ModelStatus {
    Unspecified = 0,
    Queued = 1,
    Loading = 2,
    Ready = 3,
    Failed = 4,
}
impl ModelStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MODEL_STATUS_UNSPECIFIED",
            Self::Queued => "MODEL_STATUS_QUEUED",
            Self::Loading => "MODEL_STATUS_LOADING",
            Self::Ready => "MODEL_STATUS_READY",
            Self::Failed => "MODEL_STATUS_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MODEL_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "MODEL_STATUS_QUEUED" => Some(Self::Queued),
            "MODEL_STATUS_LOADING" => Some(Self::Loading),
            "MODEL_STATUS_READY" => Some(Self::Ready),
            "MODEL_STATUS_FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod courtesy_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct CourtesyClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl<T> CourtesyClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> CourtesyClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            CourtesyClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn quote_prepared_text(
            &mut self,
            request: impl tonic::IntoRequest<super::QuotePreparedTextRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QuotePreparedTextResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.courtesy.v1.Courtesy/QuotePreparedText",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("hellas.courtesy.v1.Courtesy", "QuotePreparedText"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn quote_prompt(
            &mut self,
            request: impl tonic::IntoRequest<super::QuotePromptRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QuotePromptResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.courtesy.v1.Courtesy/QuotePrompt",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.courtesy.v1.Courtesy", "QuotePrompt"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn quote_chat_prompt(
            &mut self,
            request: impl tonic::IntoRequest<super::QuoteChatPromptRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QuoteChatPromptResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.courtesy.v1.Courtesy/QuoteChatPrompt",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("hellas.courtesy.v1.Courtesy", "QuoteChatPrompt"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn put_artifact(
            &mut self,
            request: impl tonic::IntoRequest<super::PutArtifactRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PutArtifactResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.courtesy.v1.Courtesy/PutArtifact",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.courtesy.v1.Courtesy", "PutArtifact"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_artifact(
            &mut self,
            request: impl tonic::IntoRequest<super::GetArtifactRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetArtifactResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.courtesy.v1.Courtesy/GetArtifact",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.courtesy.v1.Courtesy", "GetArtifact"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_models(
            &mut self,
            request: impl tonic::IntoRequest<super::ListModelsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListModelsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.courtesy.v1.Courtesy/ListModels",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.courtesy.v1.Courtesy", "ListModels"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn decode_tokens(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::DecodeTokensRequest,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::DecodeTokensResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.courtesy.v1.Courtesy/DecodeTokens",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.courtesy.v1.Courtesy", "DecodeTokens"));
            self.inner.streaming(req, path, codec).await
        }
        pub async fn get_stats(
            &mut self,
            request: impl tonic::IntoRequest<super::GetStatsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStatsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.courtesy.v1.Courtesy/GetStats",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.courtesy.v1.Courtesy", "GetStats"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_model_stats(
            &mut self,
            request: impl tonic::IntoRequest<super::GetModelStatsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetModelStatsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.courtesy.v1.Courtesy/GetModelStats",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.courtesy.v1.Courtesy", "GetModelStats"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod courtesy_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with CourtesyServer.
    #[async_trait]
    pub trait Courtesy: std::marker::Send + std::marker::Sync + 'static {
        async fn quote_prepared_text(
            &self,
            request: tonic::Request<super::QuotePreparedTextRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QuotePreparedTextResponse>,
            tonic::Status,
        >;
        async fn quote_prompt(
            &self,
            request: tonic::Request<super::QuotePromptRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QuotePromptResponse>,
            tonic::Status,
        >;
        async fn quote_chat_prompt(
            &self,
            request: tonic::Request<super::QuoteChatPromptRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QuoteChatPromptResponse>,
            tonic::Status,
        >;
        async fn put_artifact(
            &self,
            request: tonic::Request<super::PutArtifactRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PutArtifactResponse>,
            tonic::Status,
        >;
        async fn get_artifact(
            &self,
            request: tonic::Request<super::GetArtifactRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetArtifactResponse>,
            tonic::Status,
        >;
        async fn list_models(
            &self,
            request: tonic::Request<super::ListModelsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListModelsResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the DecodeTokens method.
        type DecodeTokensStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::DecodeTokensResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn decode_tokens(
            &self,
            request: tonic::Request<tonic::Streaming<super::DecodeTokensRequest>>,
        ) -> std::result::Result<
            tonic::Response<Self::DecodeTokensStream>,
            tonic::Status,
        >;
        async fn get_stats(
            &self,
            request: tonic::Request<super::GetStatsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStatsResponse>,
            tonic::Status,
        >;
        async fn get_model_stats(
            &self,
            request: tonic::Request<super::GetModelStatsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetModelStatsResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct CourtesyServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> CourtesyServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for CourtesyServer<T>
    where
        T: Courtesy,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/hellas.courtesy.v1.Courtesy/QuotePreparedText" => {
                    #[allow(non_camel_case_types)]
                    struct QuotePreparedTextSvc<T: Courtesy>(pub Arc<T>);
                    impl<
                        T: Courtesy,
                    > tonic::server::UnaryService<super::QuotePreparedTextRequest>
                    for QuotePreparedTextSvc<T> {
                        type Response = super::QuotePreparedTextResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::QuotePreparedTextRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Courtesy>::quote_prepared_text(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = QuotePreparedTextSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.courtesy.v1.Courtesy/QuotePrompt" => {
                    #[allow(non_camel_case_types)]
                    struct QuotePromptSvc<T: Courtesy>(pub Arc<T>);
                    impl<
                        T: Courtesy,
                    > tonic::server::UnaryService<super::QuotePromptRequest>
                    for QuotePromptSvc<T> {
                        type Response = super::QuotePromptResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::QuotePromptRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Courtesy>::quote_prompt(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = QuotePromptSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.courtesy.v1.Courtesy/QuoteChatPrompt" => {
                    #[allow(non_camel_case_types)]
                    struct QuoteChatPromptSvc<T: Courtesy>(pub Arc<T>);
                    impl<
                        T: Courtesy,
                    > tonic::server::UnaryService<super::QuoteChatPromptRequest>
                    for QuoteChatPromptSvc<T> {
                        type Response = super::QuoteChatPromptResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::QuoteChatPromptRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Courtesy>::quote_chat_prompt(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = QuoteChatPromptSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.courtesy.v1.Courtesy/PutArtifact" => {
                    #[allow(non_camel_case_types)]
                    struct PutArtifactSvc<T: Courtesy>(pub Arc<T>);
                    impl<
                        T: Courtesy,
                    > tonic::server::UnaryService<super::PutArtifactRequest>
                    for PutArtifactSvc<T> {
                        type Response = super::PutArtifactResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PutArtifactRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Courtesy>::put_artifact(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PutArtifactSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.courtesy.v1.Courtesy/GetArtifact" => {
                    #[allow(non_camel_case_types)]
                    struct GetArtifactSvc<T: Courtesy>(pub Arc<T>);
                    impl<
                        T: Courtesy,
                    > tonic::server::UnaryService<super::GetArtifactRequest>
                    for GetArtifactSvc<T> {
                        type Response = super::GetArtifactResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetArtifactRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Courtesy>::get_artifact(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetArtifactSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.courtesy.v1.Courtesy/ListModels" => {
                    #[allow(non_camel_case_types)]
                    struct ListModelsSvc<T: Courtesy>(pub Arc<T>);
                    impl<
                        T: Courtesy,
                    > tonic::server::UnaryService<super::ListModelsRequest>
                    for ListModelsSvc<T> {
                        type Response = super::ListModelsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListModelsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Courtesy>::list_models(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListModelsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.courtesy.v1.Courtesy/DecodeTokens" => {
                    #[allow(non_camel_case_types)]
                    struct DecodeTokensSvc<T: Courtesy>(pub Arc<T>);
                    impl<
                        T: Courtesy,
                    > tonic::server::StreamingService<super::DecodeTokensRequest>
                    for DecodeTokensSvc<T> {
                        type Response = super::DecodeTokensResponse;
                        type ResponseStream = T::DecodeTokensStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::DecodeTokensRequest>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Courtesy>::decode_tokens(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DecodeTokensSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.courtesy.v1.Courtesy/GetStats" => {
                    #[allow(non_camel_case_types)]
                    struct GetStatsSvc<T: Courtesy>(pub Arc<T>);
                    impl<T: Courtesy> tonic::server::UnaryService<super::GetStatsRequest>
                    for GetStatsSvc<T> {
                        type Response = super::GetStatsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetStatsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Courtesy>::get_stats(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetStatsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.courtesy.v1.Courtesy/GetModelStats" => {
                    #[allow(non_camel_case_types)]
                    struct GetModelStatsSvc<T: Courtesy>(pub Arc<T>);
                    impl<
                        T: Courtesy,
                    > tonic::server::UnaryService<super::GetModelStatsRequest>
                    for GetModelStatsSvc<T> {
                        type Response = super::GetModelStatsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetModelStatsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Courtesy>::get_model_stats(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetModelStatsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for CourtesyServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "hellas.courtesy.v1.Courtesy";
    impl<T> tonic::server::NamedService for CourtesyServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
