// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ticket {
    /// exactly 32 bytes
    #[prost(bytes = "vec", tag = "1")]
    pub request_commitment: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub amount: u64,
    #[prost(uint64, tag = "3")]
    pub ttl_ms: u64,
}
impl ::prost::Name for Ticket {
    const NAME: &'static str = "Ticket";
    const PACKAGE: &'static str = "hellas.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.v1.Ticket".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.v1.Ticket".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RunTicketRequest {
    /// exactly 32 bytes
    #[prost(bytes = "vec", tag = "1")]
    pub request_commitment: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for RunTicketRequest {
    const NAME: &'static str = "RunTicketRequest";
    const PACKAGE: &'static str = "hellas.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.v1.RunTicketRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.v1.RunTicketRequest".into()
    }
}
/// Wire protocol: zero or more WorkChunk events, terminated by exactly one
/// WorkFinished or WorkFailed, after which the stream ends. Streaming chunks
/// are transport-only; the terminal output is the object committed to by the
/// receipt.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WorkEvent {
    #[prost(oneof = "work_event::Kind", tags = "1, 2, 3")]
    pub kind: ::core::option::Option<work_event::Kind>,
}
/// Nested message and enum types in `WorkEvent`.
pub mod work_event {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        Chunk(super::WorkChunk),
        #[prost(message, tag = "2")]
        Finished(super::WorkFinished),
        #[prost(message, tag = "3")]
        Failed(super::WorkFailed),
    }
}
impl ::prost::Name for WorkEvent {
    const NAME: &'static str = "WorkEvent";
    const PACKAGE: &'static str = "hellas.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.v1.WorkEvent".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.v1.WorkEvent".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WorkChunk {
    /// Cumulative position AFTER this chunk.
    #[prost(uint64, tag = "1")]
    pub position: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub bytes: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for WorkChunk {
    const NAME: &'static str = "WorkChunk";
    const PACKAGE: &'static str = "hellas.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.v1.WorkChunk".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.v1.WorkChunk".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WorkFinished {
    /// Complete output object. Symbolic text uses little-endian u32 token IDs.
    /// Opaque uses exact UTF-8 JSON bytes.
    #[prost(bytes = "vec", tag = "1")]
    pub output: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub receipt: ::core::option::Option<ReceiptEnvelope>,
    #[prost(enumeration = "FinishStatus", tag = "3")]
    pub status: i32,
    #[prost(uint64, tag = "4")]
    pub total_units: u64,
}
impl ::prost::Name for WorkFinished {
    const NAME: &'static str = "WorkFinished";
    const PACKAGE: &'static str = "hellas.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.v1.WorkFinished".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.v1.WorkFinished".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WorkFailed {
    /// Units emitted before failure (tokens for symbolic text, bytes for opaque).
    #[prost(uint64, tag = "1")]
    pub position: u64,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
impl ::prost::Name for WorkFailed {
    const NAME: &'static str = "WorkFailed";
    const PACKAGE: &'static str = "hellas.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.v1.WorkFailed".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.v1.WorkFailed".into()
    }
}
/// Canonical hellas-core SignedReceipt encoded as strict dag-cbor.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReceiptEnvelope {
    #[prost(bytes = "vec", tag = "1")]
    pub dag_cbor: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for ReceiptEnvelope {
    const NAME: &'static str = "ReceiptEnvelope";
    const PACKAGE: &'static str = "hellas.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.v1.ReceiptEnvelope".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.v1.ReceiptEnvelope".into()
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FinishStatus {
    Unspecified = 0,
    EndOfSequence = 1,
    MaxOutput = 2,
    Cancelled = 3,
}
impl FinishStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "FINISH_STATUS_UNSPECIFIED",
            Self::EndOfSequence => "FINISH_STATUS_END_OF_SEQUENCE",
            Self::MaxOutput => "FINISH_STATUS_MAX_OUTPUT",
            Self::Cancelled => "FINISH_STATUS_CANCELLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FINISH_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "FINISH_STATUS_END_OF_SEQUENCE" => Some(Self::EndOfSequence),
            "FINISH_STATUS_MAX_OUTPUT" => Some(Self::MaxOutput),
            "FINISH_STATUS_CANCELLED" => Some(Self::Cancelled),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod execute_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct ExecuteClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl<T> ExecuteClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ExecuteClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ExecuteClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn run_ticket(
            &mut self,
            request: impl tonic::IntoRequest<super::RunTicketRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::WorkEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.v1.Execute/RunTicket",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.v1.Execute", "RunTicket"));
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod execute_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ExecuteServer.
    #[async_trait]
    pub trait Execute: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the RunTicket method.
        type RunTicketStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::WorkEvent, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn run_ticket(
            &self,
            request: tonic::Request<super::RunTicketRequest>,
        ) -> std::result::Result<tonic::Response<Self::RunTicketStream>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct ExecuteServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ExecuteServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ExecuteServer<T>
    where
        T: Execute,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/hellas.v1.Execute/RunTicket" => {
                    #[allow(non_camel_case_types)]
                    struct RunTicketSvc<T: Execute>(pub Arc<T>);
                    impl<
                        T: Execute,
                    > tonic::server::ServerStreamingService<super::RunTicketRequest>
                    for RunTicketSvc<T> {
                        type Response = super::WorkEvent;
                        type ResponseStream = T::RunTicketStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RunTicketRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Execute>::run_ticket(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RunTicketSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ExecuteServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "hellas.v1.Execute";
    impl<T> tonic::server::NamedService for ExecuteServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
