//! Sans-io peer registry and admission policy primitives.
//!
//! This module is the pure state engine for peer facts. It intentionally has no
//! transport, runtime, clock, or storage dependencies. Callers pass timestamps
//! and observations in, and the registry returns deterministic state changes and
//! admission decisions.
//!
//! Most application code should use [`PeerManager`] instead of calling
//! [`PeerRegistry::apply`] directly. The intended layering is:
//!
//! - a transport/discovery driver owns discovery streams and records facts here
//!   before notifying application code;
//! - generated or hand-written RPC clients acquire/release request permits here
//!   around actual RPC calls;
//! - RPC servers record inbound calls with `observe_inbound_request` for
//!   accounting and admission, but do not infer service capabilities from those
//!   calls;
//! - application code queries the current registry view, usually through a
//!   manager snapshot/view API, rather than hand-feeding events.
//!
//! In other words, the registry is the source of truth, not the discovery task
//! and not an event stream. Events are useful for notification, but polling
//! events should never be required to keep peer state correct.
//!
//! Querying from the pure registry returns borrowed entries:
//!
//! ```ignore
//! if let Some(peer) = registry.get(peer_id) {
//!     if let Some(courtesy) = peer.service::<CourtesyService>() {
//!         println!("courtesy status: {:?}", courtesy.status);
//!     }
//! }
//! ```
//!
//! `PeerManager` exposes snapshots and closure-based reads instead of long-lived
//! `Arc<PeerEntry>` handles, so callers do not accidentally hold locks or
//! depend on stale mutable state.

mod admission;
mod directory;
mod id;
mod manager;
mod registry;
mod security;

pub use admission::{
    AcquireDenied, InboundPeerObservation, Outcome, PeerExtractor, Permit, RequestKind,
};
pub use directory::{
    COURTESY_SERVICE_ALPN, EXECUTE_SERVICE_ALPN, InboundAdmission, InboundRequestPolicy,
    LEGACY_EXECUTE_SERVICE_ALPN, LEGACY_NODE_SERVICE_ALPN, NODE_SERVICE_ALPN, OPAQUE_SERVICE_ALPN,
    PeerDirectory, PeerDirectoryConfig, SYMBOLIC_SERVICE_ALPN, ServiceAlias,
};
pub use id::PeerId;
#[cfg(feature = "iroh")]
pub use manager::iroh_service_alpn;
#[cfg(any(feature = "iroh-client", feature = "iroh-server"))]
pub use manager::IrohPeerExtractor;
#[cfg(feature = "iroh-client")]
pub use manager::{IrohRpcPool, IrohRpcPoolError};
pub use manager::{
    PeerManager, PeerManagerError, PeerServiceSession, PeerSession, RpcObservation, RpcPermitGuard,
};
pub use registry::{
    DiscoverySource, PeerChange, PeerEntry, PeerEvent, PeerRegistry, PeerRegistryConfig,
    ServiceObservation, ServiceState, ServiceStatus,
};
pub use security::{AuthLevel, TransportSecurity};

/// Type-level service identity used by typed peer queries and request kinds.
///
/// One marker type per `.proto` service; generated by `crates/rpc/build.rs`
/// from the schema. Carries both the gRPC service FQN and the iroh ALPN that
/// the transport adapter dials.
pub trait RpcService {
    /// Fully-qualified gRPC service name (`package.Service`).
    const NAME: &'static str;
    /// Iroh ALPN derived as `/{NAME}/1.0`. Constant so it can be referenced
    /// without allocation from transport adapters.
    const ALPN: &'static str;
}

/// Server-side adapter that the generated managed server wrappers use to
/// translate a gRPC path string into a typed inbound admission policy.
///
/// Exists because bytes off the network arrive as a path string and only
/// codegen can know which method that string corresponds to. The trait makes
/// that translation private to the generated impl — callers never write
/// method paths or method names themselves.
pub trait RpcServiceSpec: RpcService {
    /// Return the policy for a request landing at `path`, or `None` if the
    /// path does not match any of this service's methods (in which case the
    /// inner tonic dispatcher will reply with `UNIMPLEMENTED`).
    fn inbound_policy(path: &str) -> Option<directory::InboundRequestPolicy>;
}

/// Type-level RPC method identity.
///
/// Generated clients emit one method marker per `rpc … { … }` so application
/// code never passes method names, gRPC paths, or request/response types as
/// raw strings. The trait carries everything codegen needs to lower a typed
/// call site into the right wire shape: the typed message types, the gRPC
/// path string the transport speaks, default admission cost, and unary-vs-
/// streaming flags.
pub trait RpcMethod {
    type Service: RpcService;
    type Request: prost::Message + Default + 'static;
    type Response: prost::Message + Default + 'static;
    /// Method name as it appears in the `.proto` (e.g. `"GetNodeInfo"`).
    const NAME: &'static str;
    /// Fully-qualified gRPC path (`/package.Service/Method`). Used by the
    /// inbound admission layer to match incoming requests and by codegen
    /// to construct outbound tonic calls.
    const GRPC_PATH: &'static str;
    /// Per-method admission cost. Codegen seeds this from the schema;
    /// callers can override per-call via the future `with_cost` builder.
    const DEFAULT_COST: f32 = 1.0;
    /// True if the request side is `stream`-typed in the .proto.
    const REQUEST_STREAMING: bool = false;
    /// True if the response side is `stream`-typed in the .proto.
    const RESPONSE_STREAMING: bool = false;
}

// Back-compat aliases — old name still resolves while consumers migrate.
// TODO(step 8 cleanup): delete once no caller references ServiceKey/MethodKey.
pub use RpcMethod as MethodKey;
pub use RpcService as ServiceKey;
