//! Sans-io peer registry and admission policy primitives.
//!
//! This module is the pure state engine for peer facts. It intentionally has no
//! transport, runtime, clock, or storage dependencies. Callers pass timestamps
//! and observations in, and the registry returns deterministic state changes and
//! admission decisions.
//!
//! Most application code should use [`PeerManager`] instead of calling
//! [`PeerRegistry::apply`] directly. The intended layering is:
//!
//! - a transport/discovery driver owns discovery streams and records facts here
//!   before notifying application code;
//! - generated or hand-written RPC clients acquire/release request permits here
//!   around actual RPC calls;
//! - RPC servers record inbound calls with `observe_inbound_request` for
//!   accounting and admission, but do not infer service capabilities from those
//!   calls;
//! - application code queries the current registry view, usually through a
//!   manager snapshot/view API, rather than hand-feeding events.
//!
//! In other words, the registry is the source of truth, not the discovery task
//! and not an event stream. Events are useful for notification, but polling
//! events should never be required to keep peer state correct.
//!
//! Querying from the pure registry returns borrowed entries:
//!
//! ```ignore
//! if let Some(peer) = registry.get(peer_id) {
//!     if let Some(courtesy) = peer.service::<CourtesyService>() {
//!         println!("courtesy status: {:?}", courtesy.status);
//!     }
//! }
//! ```
//!
//! `PeerManager` exposes snapshots and closure-based reads instead of long-lived
//! `Arc<PeerEntry>` handles, so callers do not accidentally hold locks or
//! depend on stale mutable state.

mod admission;
mod directory;
mod id;
mod manager;
mod registry;
mod security;

pub use admission::{AcquireDenied, InboundPeerObservation, PeerExtractor};
pub use directory::{
    InboundAdmission, InboundRequestPolicy, PeerDirectory, PeerDirectoryConfig,
};
pub use id::PeerId;
#[cfg(any(feature = "iroh-client", feature = "iroh-server"))]
pub use manager::IrohPeerExtractor;
#[cfg(feature = "iroh-client")]
pub use manager::{IrohPeerHandle, IrohRpcPool, IrohRpcPoolError, IrohTarget, IrohTransport};
pub use manager::{
    PeerManager, PeerManagerError, PeerServiceSession, PeerSession, RpcObservation, RpcPermitGuard,
};
pub use registry::{
    DiscoverySource, PeerChange, PeerEntry, PeerEvent, PeerRegistry, PeerRegistryConfig,
    ServiceObservation, ServiceState, ServiceStatus,
};
pub use security::{AuthLevel, TransportSecurity};

// Trait re-exports below are emitted as `peers::RpcService` etc by the
// generated marker files (`include!()`'d at the crate root via `pub mod
// service` and `pub mod client`). Note `RpcServiceSpec`, `IrohServiceSpec`,
// `RpcService`, `RpcMethod`, and `GrpcMethodSpec` are defined as items in
// this module below — they are directly reachable as `crate::peers::*` and
// don't need explicit `pub use`.

/// Transport-independent service identity. One marker type per `.proto`
/// service (generated by `crates/rpc/build.rs`), carrying only the fully-
/// qualified service name so accounting code can name a service without
/// pulling in any transport- or codec-specific concept.
///
/// Transport- and codec-specific facts (iroh ALPN, gRPC service path, etc.)
/// live on companion traits like [`IrohServiceSpec`] and [`GrpcMethodSpec`]
/// so that adding e.g. a `WebSocketServiceSpec` does not require changing
/// the core marker.
pub trait RpcService {
    /// Fully-qualified service name (`package.Service`).
    const NAME: &'static str;
}

/// Iroh-transport-specific service facts. Generated alongside the
/// [`RpcService`] impl for any service that participates in iroh dialing.
///
/// `tonic::server::NamedService` is a supertrait because the iroh transport's
/// `IrohConnect` blanket impl is keyed by `NamedService::NAME`, so we want any
/// `IrohServiceSpec` marker to be directly dialable as `S::connect(endpoint,
/// addr)` without a second bound at every call site.
#[cfg(any(feature = "iroh-client", feature = "iroh-server"))]
pub trait IrohServiceSpec: RpcService + tonic::server::NamedService {
    /// Iroh ALPN derived as `/{NAME}/1.0`. Constant so it can be referenced
    /// without allocation from transport adapters.
    const ALPN: &'static str;
}

/// Server-side adapter that the generated managed server wrappers use to
/// translate a gRPC path string into a typed inbound admission policy.
///
/// Exists because bytes off the network arrive as a path string and only
/// codegen can know which method that string corresponds to. The trait makes
/// that translation private to the generated impl — callers never write
/// method paths or method names themselves.
pub trait RpcServiceSpec: RpcService {
    /// Return the policy for a request landing at `path`, or `None` if the
    /// path does not match any of this service's methods (in which case the
    /// inner tonic dispatcher will reply with `UNIMPLEMENTED`).
    fn inbound_policy(path: &str) -> Option<directory::InboundRequestPolicy>;
}

/// Transport-independent RPC method identity.
///
/// Generated clients emit one method marker per `rpc … { … }`. The core
/// trait only carries the service back-reference and method name — anything
/// codec-specific (gRPC wire shape, prost types, streaming flags) lives on
/// [`GrpcMethodSpec`] so future codecs can add their own companion traits
/// without changing the core marker.
pub trait RpcMethod {
    type Service: RpcService;
    /// Method name as it appears in the `.proto` (e.g. `"GetNodeInfo"`).
    const NAME: &'static str;
}

/// gRPC/tonic-specific wire facts about an [`RpcMethod`]. Generated
/// alongside the core marker for every method that participates in a gRPC
/// service.
pub trait GrpcMethodSpec: RpcMethod {
    type Request: prost::Message + Default + 'static;
    type Response: prost::Message + Default + 'static;
    /// Fully-qualified gRPC path (`/package.Service/Method`). Used by the
    /// inbound admission layer to match incoming requests and by codegen
    /// to construct outbound tonic calls.
    const GRPC_PATH: &'static str;
    /// True if the request side is `stream`-typed in the .proto.
    const REQUEST_STREAMING: bool = false;
    /// True if the response side is `stream`-typed in the .proto.
    const RESPONSE_STREAMING: bool = false;
}
