//! Sans-io peer registry and admission policy primitives.
//!
//! This module is the pure state engine for peer facts. It intentionally has no
//! transport, runtime, clock, or storage dependencies. Callers pass timestamps
//! and observations in, and the registry returns deterministic state changes and
//! admission decisions.
//!
//! Most application code should use [`PeerManager`] instead of calling
//! [`PeerRegistry::apply`] directly. The intended layering is:
//!
//! - a transport/discovery driver owns discovery streams and records facts here
//!   before notifying application code;
//! - generated or hand-written RPC clients acquire/release request permits here
//!   around actual RPC calls;
//! - RPC servers record inbound calls with `observe_inbound_request` for
//!   accounting and admission, but do not infer service capabilities from those
//!   calls;
//! - application code queries the current registry view, usually through a
//!   manager snapshot/view API, rather than hand-feeding events.
//!
//! In other words, the registry is the source of truth, not the discovery task
//! and not an event stream. Events are useful for notification, but polling
//! events should never be required to keep peer state correct.

mod admission;
mod directory;
mod id;
mod manager;
mod registry;
mod security;

pub use admission::{AcquireDenied, InboundPeerObservation, PeerExtractor};
pub use directory::{
    InboundAdmission, InboundRequestPolicy, PeerDirectory, PeerDirectoryConfig,
};
pub use id::PeerId;
pub use manager::{
    PeerManager, PeerManagerError, PeerServiceSession, PeerSession, RpcObservation,
    RpcPermitGuard,
};
pub use registry::{
    DiscoverySource, PeerChange, PeerEntry, PeerEvent, PeerRegistry, PeerRegistryConfig,
    ServiceObservation, ServiceState, ServiceStatus,
};
pub use security::{AuthLevel, TransportSecurity};

/// Transport-independent service identity. One marker type per `.proto`
/// service (generated by `crates/rpc/build.rs`).
///
/// This trait is the bridge between the peer registry's notion of "service"
/// (a stable name, used for service-level admission and accounting) and
/// codegen-emitted markers. Concrete transport bindings (iroh, h2, ws)
/// live on the `hellas_wire::ServiceMarker` companion trait, which the
/// generated impls also satisfy.
pub trait RpcService {
    /// Fully-qualified service name (`package.Service`).
    const NAME: &'static str;
}

/// Transport-independent RPC method identity. Generated clients emit one
/// marker type per `rpc … { … }` block.
pub trait RpcMethod {
    type Service: RpcService;
    /// Method name as it appears in the `.proto` (e.g. `"GetNodeInfo"`).
    const NAME: &'static str;
}
