//! Causal-LM decode driver for the executor.
//!
//! # Overview
//!
//! The runner drives a single text-generation request to completion,
//! emitting generated tokens to a streaming callback. It's the only
//! place in the executor that calls into catgrad's LLM execution
//! surface; everything else (cache, scheduling, quoting) is plain data.
//!
//! # Algorithm
//!
//! 1. **Exact-output replay.** If the request commitment matches a
//!    previously-served request, the cached output tokens are streamed
//!    back without touching the model.
//!
//! 2. **Prefill.** A single batched call against the bound program's
//!    [`prefill`](hellas_runtime::runtime::BoundProgramText::prefill) on
//!    top of the resolved starting state (cold-start: program's genesis
//!    state; anchored: a previously-stored receipt). Returns a
//!    [`TextDecoder`] positioned to commit the first predicted token.
//!
//! 3. **Decode loop.** Peek the predicted token, check stop tokens,
//!    [`commit_next`] to emit-and-advance, repeat to `max_new_tokens`.
//!    Each iteration leaves the decoder fully receipt-aligned.
//!
//! On completion the runner consumes the decoder into a
//! [`TextState`](hellas_runtime::runtime::TextState), inserts that state
//! into the receipt store (so future anchored requests can reference
//! it), and stores the emitted token sequence in the exact-replay cache.
//!
//! # Why no generic-over-stepper trait
//!
//! Earlier versions abstracted the decode loop over a `CausalStepper`
//! trait so a fake in-memory implementation could substitute for the
//! catgrad session in tests. The trait was load-bearing for the
//! split-stability test approach. Without that, the runner is concrete
//! on `TextDecoder<ExecBackend>` and tested via end-to-end smoke runs.

use crate::backend::ExecBackend;
use crate::programs::{ExecutionContext, ExecutionStart};
use crate::state::{Invocation, StopReason};
use catgrad::category::core::Shape;
use catgrad::interpreter;
use hellas_rpc::ExecutorError;
use hellas_rpc::encode_token_ids;
use hellas_runtime::runtime::{
    BoundProgramText, BreakReason, DecodeLoopError, DecodeOutcome as DecoderOutcome, TextDecoder,
    run_decode,
};
use std::sync::Arc;
use std::time::Instant;
use tokio_util::sync::CancellationToken;

/// Terminal output of a completed decode. Worker maps this onto a
/// `Termination::Completed` for the actor.
#[derive(Debug, Clone)]
pub struct DecodeOutcome {
    pub total_tokens: u64,
    pub stop_reason: StopReason,
    /// All tokens generated by this decode, in order. Needed to build
    /// the receipt result.
    pub output_tokens: Vec<u32>,
}

/// Public entry point. Wires the catgrad text decoder, runs the decode
/// loop, and writes the result back to the [`ExecutionContext`] caches.
///
/// `cancel` is polled between decode iterations; when triggered, the
/// loop exits with `StopReason::Cancelled` and the partial post-state is
/// still receipt-aligned (every step ends with `commit_next` complete).
/// Cancelled runs do NOT populate the exact-replay cache (they would
/// poison future identical requests with a partial output) but they DO
/// populate the receipt store so anchored requests can resume.
pub fn run_cached_program_streaming(
    program: &ExecutionContext,
    start: &ExecutionStart,
    invocation: &Invocation,
    stream_batch_size: u32,
    cancel: &CancellationToken,
    mut on_progress: impl FnMut(u64, &[u8]),
) -> Result<DecodeOutcome, ExecutorError> {
    let started_at = Instant::now();
    let batch_size = usize::try_from(stream_batch_size.max(1))
        .unwrap_or(usize::MAX)
        .max(1);
    let prompt_tokens = invocation.input_ids.len();

    if let Some(cached) = start.cached.as_ref() {
        info!(
            prompt_tokens,
            cached_output_tokens = cached.output_tokens.len(),
            first_token_total_ms = started_at.elapsed().as_millis(),
            "first token ready (replay)"
        );
        let mut emitted = 0u64;
        for chunk in cached.output_tokens.chunks(batch_size) {
            emitted = emitted.saturating_add(chunk.len() as u64);
            on_progress(emitted, &encode_token_ids(chunk));
        }
        return Ok(DecodeOutcome {
            total_tokens: cached.output_tokens.len() as u64,
            stop_reason: cached.stop_reason,
            output_tokens: cached.output_tokens.to_vec(),
        });
    }

    let session_start = Instant::now();
    let bound = program.bound_program();
    let input_tensor = interpreter::tensor(
        &bound.interpreter().backend,
        Shape(vec![1, prompt_tokens]),
        invocation.input_ids.clone(),
    )
    .map_err(|error| {
        ExecutorError::WeightsError(format!("failed to build input tensor: {error:?}"))
    })?;
    let mut decoder: TextDecoder<ExecBackend> =
        Arc::clone(bound).prefill(&start.initial_state, &input_tensor)?;

    info!(
        prompt_tokens,
        first_token_total_ms = started_at.elapsed().as_millis(),
        session_start_ms = session_start.elapsed().as_millis(),
        "first token ready"
    );

    let DecodeLoopOutput {
        stop_reason,
        output_tokens,
    } = run_decode_loop(
        &mut decoder,
        invocation.max_new_tokens,
        &invocation.stop_token_ids,
        batch_size,
        cancel,
        &mut on_progress,
    )?;

    let total_tokens = output_tokens.len() as u64;
    let final_state = decoder.into_text_state(start.commitment_id, &output_tokens)?;
    program.cache_receipt(Arc::new(final_state));
    // Skip continuation cache on cancellation: an identical future request
    // expects the deterministic full output, not a partial one. The
    // receipt store is fine to populate — a real receipt for "we ran this
    // far" is always honest.
    let output_tokens_for_outcome = output_tokens.clone();
    if !matches!(stop_reason, StopReason::Cancelled) {
        program.cache_continuation(start.commitment_id, output_tokens, stop_reason);
    }

    Ok(DecodeOutcome {
        total_tokens,
        stop_reason,
        output_tokens: output_tokens_for_outcome,
    })
}

struct DecodeLoopOutput {
    stop_reason: StopReason,
    output_tokens: Vec<u32>,
}

/// Decode loop: drives [`run_decode`] over the decoder, layering
/// cancellation + batched progress emission on top via the per-token
/// callback.
///
/// After each `commit_next` the decoder is fully receipt-aligned, so
/// breaking out (stop token or cancellation) always leaves
/// `decoder.position == output_tokens.len()` — the invariant
/// `into_text_state` requires.
///
/// **Cancellation timing:** the cancel check happens *after* the
/// current token has been committed and recorded. A cancelled
/// response therefore includes the token that was already in flight
/// when cancel fired. The previous bespoke loop checked cancel
/// *before* peeking — net effect is up to one extra token in the
/// cancelled output.
fn run_decode_loop(
    decoder: &mut TextDecoder<ExecBackend>,
    max_new_tokens: u32,
    stop_token_ids: &[i32],
    batch_size: usize,
    cancel: &CancellationToken,
    on_progress: &mut impl FnMut(u64, &[u8]),
) -> Result<DecodeLoopOutput, ExecutorError> {
    let mut output_tokens: Vec<u32> = Vec::new();
    let mut pending_batch: Vec<u32> = Vec::with_capacity(batch_size);
    let mut generated: u64 = 0;

    let (_, outcome) = run_decode::<_, _, std::convert::Infallible>(
        decoder,
        max_new_tokens,
        stop_token_ids,
        |token| {
            // Push first so output_tokens length tracks decoder.position.
            generated += 1;
            output_tokens.push(token);
            pending_batch.push(token);
            if pending_batch.len() >= batch_size {
                let chunk = encode_token_ids(&pending_batch);
                on_progress(generated, &chunk);
                pending_batch.clear();
            }
            // Then check cancellation: signals run_decode to stop AFTER
            // this token is committed and reported.
            if cancel.is_cancelled() {
                Ok(std::ops::ControlFlow::Break(BreakReason::Cancelled))
            } else {
                Ok(std::ops::ControlFlow::Continue(()))
            }
        },
    )
    .map_err(|err| match err {
        DecodeLoopError::Decoder(e) => ExecutorError::from(e),
        DecodeLoopError::Sink(_) => unreachable!("Infallible sink"),
    })?;

    if !pending_batch.is_empty() {
        let chunk = encode_token_ids(&pending_batch);
        on_progress(generated, &chunk);
    }

    let stop_reason = match outcome {
        DecoderOutcome::EndOfSequence => StopReason::EndOfSequence,
        DecoderOutcome::MaxTokens => StopReason::MaxNewTokens,
        DecoderOutcome::Cancelled => StopReason::Cancelled,
        // Executor doesn't use the StopSequence break path — only the
        // EndOfSequence (parser-level stop tokens) and Cancelled
        // paths. Treat as EndOfSequence defensively if it ever fires.
        DecoderOutcome::StopSequence => StopReason::EndOfSequence,
    };

    Ok(DecodeLoopOutput {
        stop_reason,
        output_tokens,
    })
}
