syntax = "proto3";

package hellas;

import "execute.proto";
import "node.proto";

service Node {
  rpc HealthCheck(HealthCheckRequest) returns (HealthCheckResponse);
  rpc GetKnownPeers(GetKnownPeersRequest) returns (GetKnownPeersResponse);
}

service Execute {
  rpc GetQuote(GetQuoteRequest) returns (GetQuoteResponse);
  rpc QuotePrompt(QuotePromptRequest) returns (QuotePromptResponse);
  rpc ListModels(ListModelsRequest) returns (ListModelsResponse);
  rpc DecodeTokens(stream DecodeTokensRequest) returns (stream DecodeTokensResponse);
  rpc Execute(ExecuteRequest) returns (ExecuteResponse);
  rpc ExecuteStatus(ExecuteStatusRequest) returns (ExecuteStatusResponse);
  rpc ExecuteStream(ExecuteStatusRequest) returns (stream ExecuteStreamEvent);
  rpc ExecuteResult(ExecuteResultRequest) returns (ExecuteResultResponse);
}

message Presence {
  string hf_id = 1;
  string req_id = 2;
  string peer_id = 3;
  uint64 ttl_ms = 4;
  bool is_executor = 5;
}
