syntax = "proto3";

package hellas;

import "execute.proto";
import "node.proto";

service Node {
  rpc GetNodeInfo(GetNodeInfoRequest) returns (GetNodeInfoResponse);
  rpc GetKnownPeers(GetKnownPeersRequest) returns (GetKnownPeersResponse);
}

service Execute {
  rpc GetQuote(GetQuoteRequest) returns (GetQuoteResponse);
  rpc QuotePrompt(QuotePromptRequest) returns (QuotePromptResponse);
  rpc QuoteChatPrompt(QuoteChatPromptRequest) returns (QuoteChatPromptResponse);
  rpc ListModels(ListModelsRequest) returns (ListModelsResponse);
  rpc DecodeTokens(stream DecodeTokensRequest) returns (stream DecodeTokensResponse);
  rpc Execute(ExecuteRequest) returns (stream ExecuteStreamEvent);
  rpc GetStats(GetStatsRequest) returns (GetStatsResponse);
  rpc GetModelStats(GetModelStatsRequest) returns (GetModelStatsResponse);
}

message Presence {
  string hf_id = 1;
  string req_id = 2;
  string peer_id = 3;
  uint64 ttl_ms = 4;
  bool is_executor = 5;
}
