syntax = "proto3";

package hellas;

import "execute.proto";
import "node.proto";

service Node {
  rpc HealthCheck(HealthCheckRequest) returns (HealthCheckResponse);
}

service Execute {
    rpc GetQuote(GetQuoteRequest) returns (GetQuoteResponse);
    rpc GetGraph(GetGraphRequest) returns (GetGraphResponse);
    rpc Execute(ExecuteRequest) returns (ExecuteResponse);
    rpc ExecuteStatus(ExecuteStatusRequest) returns (ExecuteStatusResponse);
    rpc ExecuteStream(ExecuteStatusRequest) returns (stream ExecuteStatusDiff);
    rpc ExecuteResult(ExecuteResultRequest) returns (ExecuteResultResponse);
}
