// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetQuoteRequest {
    #[prost(string, tag = "1")]
    pub huggingface_model_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub huggingface_revision: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub model_config_json: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub graph: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub input: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "6")]
    pub prompt_tokens: u32,
    #[prost(uint32, tag = "7")]
    pub max_new_tokens: u32,
    #[prost(uint32, repeated, tag = "8")]
    pub stop_token_ids: ::prost::alloc::vec::Vec<u32>,
}
impl ::prost::Name for GetQuoteRequest {
    const NAME: &'static str = "GetQuoteRequest";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetQuoteRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetQuoteRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetQuoteResponse {
    #[prost(string, tag = "1")]
    pub quote_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub amount: u64,
}
impl ::prost::Name for GetQuoteResponse {
    const NAME: &'static str = "GetQuoteResponse";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetQuoteResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetQuoteResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteRequest {
    #[prost(string, tag = "1")]
    pub quote_id: ::prost::alloc::string::String,
    #[prost(uint32, optional, tag = "2")]
    pub stream_batch_size: ::core::option::Option<u32>,
}
impl ::prost::Name for ExecuteRequest {
    const NAME: &'static str = "ExecuteRequest";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.ExecuteRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.ExecuteRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteResponse {
    #[prost(string, tag = "1")]
    pub execution_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub quote_id: ::prost::alloc::string::String,
}
impl ::prost::Name for ExecuteResponse {
    const NAME: &'static str = "ExecuteResponse";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.ExecuteResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.ExecuteResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteStatusRequest {
    #[prost(string, tag = "1")]
    pub execution_id: ::prost::alloc::string::String,
}
impl ::prost::Name for ExecuteStatusRequest {
    const NAME: &'static str = "ExecuteStatusRequest";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.ExecuteStatusRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.ExecuteStatusRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteStatusResponse {
    #[prost(enumeration = "ExecutionStatus", tag = "1")]
    pub status: i32,
    #[prost(uint64, tag = "2")]
    pub progress: u64,
}
impl ::prost::Name for ExecuteStatusResponse {
    const NAME: &'static str = "ExecuteStatusResponse";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.ExecuteStatusResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.ExecuteStatusResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteSnapshot {
    #[prost(enumeration = "ExecutionStatus", tag = "1")]
    pub status: i32,
    #[prost(uint64, tag = "2")]
    pub progress: u64,
    #[prost(bytes = "vec", tag = "3")]
    pub output: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for ExecuteSnapshot {
    const NAME: &'static str = "ExecuteSnapshot";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.ExecuteSnapshot".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.ExecuteSnapshot".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteProgress {
    #[prost(enumeration = "ExecutionStatus", tag = "1")]
    pub status: i32,
    #[prost(uint64, tag = "2")]
    pub progress: u64,
    #[prost(bytes = "vec", tag = "3")]
    pub output_chunk: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for ExecuteProgress {
    const NAME: &'static str = "ExecuteProgress";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.ExecuteProgress".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.ExecuteProgress".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteStreamEvent {
    #[prost(oneof = "execute_stream_event::Event", tags = "1, 2")]
    pub event: ::core::option::Option<execute_stream_event::Event>,
}
/// Nested message and enum types in `ExecuteStreamEvent`.
pub mod execute_stream_event {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "1")]
        Snapshot(super::ExecuteSnapshot),
        #[prost(message, tag = "2")]
        Progress(super::ExecuteProgress),
    }
}
impl ::prost::Name for ExecuteStreamEvent {
    const NAME: &'static str = "ExecuteStreamEvent";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.ExecuteStreamEvent".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.ExecuteStreamEvent".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteResultRequest {
    #[prost(string, tag = "1")]
    pub execution_id: ::prost::alloc::string::String,
}
impl ::prost::Name for ExecuteResultRequest {
    const NAME: &'static str = "ExecuteResultRequest";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.ExecuteResultRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.ExecuteResultRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteResultResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub output: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for ExecuteResultResponse {
    const NAME: &'static str = "ExecuteResultResponse";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.ExecuteResultResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.ExecuteResultResponse".into()
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExecutionStatus {
    Unspecified = 0,
    Pending = 1,
    Running = 2,
    Completed = 3,
    Failed = 4,
}
impl ExecutionStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "UNSPECIFIED",
            Self::Pending => "PENDING",
            Self::Running => "RUNNING",
            Self::Completed => "COMPLETED",
            Self::Failed => "FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNSPECIFIED" => Some(Self::Unspecified),
            "PENDING" => Some(Self::Pending),
            "RUNNING" => Some(Self::Running),
            "COMPLETED" => Some(Self::Completed),
            "FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthCheckRequest {}
impl ::prost::Name for HealthCheckRequest {
    const NAME: &'static str = "HealthCheckRequest";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.HealthCheckRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.HealthCheckRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthCheckResponse {
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub uptime_seconds: u64,
    #[prost(string, tag = "3")]
    pub node_id: ::prost::alloc::string::String,
}
impl ::prost::Name for HealthCheckResponse {
    const NAME: &'static str = "HealthCheckResponse";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.HealthCheckResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.HealthCheckResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetKnownPeersRequest {
    #[prost(string, tag = "1")]
    pub service_alpn: ::prost::alloc::string::String,
}
impl ::prost::Name for GetKnownPeersRequest {
    const NAME: &'static str = "GetKnownPeersRequest";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetKnownPeersRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetKnownPeersRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetKnownPeersResponse {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub peer_ids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
impl ::prost::Name for GetKnownPeersResponse {
    const NAME: &'static str = "GetKnownPeersResponse";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.GetKnownPeersResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.GetKnownPeersResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Presence {
    #[prost(string, tag = "1")]
    pub hf_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub req_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub peer_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub ttl_ms: u64,
    #[prost(bool, tag = "5")]
    pub is_executor: bool,
}
impl ::prost::Name for Presence {
    const NAME: &'static str = "Presence";
    const PACKAGE: &'static str = "hellas";
    fn full_name() -> ::prost::alloc::string::String {
        "hellas.Presence".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/hellas.Presence".into()
    }
}
/// Generated client implementations.
pub mod node_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct NodeClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl<T> NodeClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> NodeClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            NodeClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn health_check(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthCheckRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HealthCheckResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/hellas.Node/HealthCheck");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("hellas.Node", "HealthCheck"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_known_peers(
            &mut self,
            request: impl tonic::IntoRequest<super::GetKnownPeersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetKnownPeersResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.Node/GetKnownPeers",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("hellas.Node", "GetKnownPeers"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod node_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with NodeServer.
    #[async_trait]
    pub trait Node: std::marker::Send + std::marker::Sync + 'static {
        async fn health_check(
            &self,
            request: tonic::Request<super::HealthCheckRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HealthCheckResponse>,
            tonic::Status,
        >;
        async fn get_known_peers(
            &self,
            request: tonic::Request<super::GetKnownPeersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetKnownPeersResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct NodeServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> NodeServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for NodeServer<T>
    where
        T: Node,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/hellas.Node/HealthCheck" => {
                    #[allow(non_camel_case_types)]
                    struct HealthCheckSvc<T: Node>(pub Arc<T>);
                    impl<T: Node> tonic::server::UnaryService<super::HealthCheckRequest>
                    for HealthCheckSvc<T> {
                        type Response = super::HealthCheckResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HealthCheckRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Node>::health_check(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HealthCheckSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.Node/GetKnownPeers" => {
                    #[allow(non_camel_case_types)]
                    struct GetKnownPeersSvc<T: Node>(pub Arc<T>);
                    impl<
                        T: Node,
                    > tonic::server::UnaryService<super::GetKnownPeersRequest>
                    for GetKnownPeersSvc<T> {
                        type Response = super::GetKnownPeersResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetKnownPeersRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Node>::get_known_peers(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetKnownPeersSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for NodeServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "hellas.Node";
    impl<T> tonic::server::NamedService for NodeServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
/// Generated client implementations.
pub mod execute_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct ExecuteClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl<T> ExecuteClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ExecuteClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ExecuteClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get_quote(
            &mut self,
            request: impl tonic::IntoRequest<super::GetQuoteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetQuoteResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/hellas.Execute/GetQuote");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("hellas.Execute", "GetQuote"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn execute(
            &mut self,
            request: impl tonic::IntoRequest<super::ExecuteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExecuteResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/hellas.Execute/Execute");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("hellas.Execute", "Execute"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn execute_status(
            &mut self,
            request: impl tonic::IntoRequest<super::ExecuteStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExecuteStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.Execute/ExecuteStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.Execute", "ExecuteStatus"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn execute_stream(
            &mut self,
            request: impl tonic::IntoRequest<super::ExecuteStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ExecuteStreamEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.Execute/ExecuteStream",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.Execute", "ExecuteStream"));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn execute_result(
            &mut self,
            request: impl tonic::IntoRequest<super::ExecuteResultRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExecuteResultResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/hellas.Execute/ExecuteResult",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("hellas.Execute", "ExecuteResult"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod execute_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ExecuteServer.
    #[async_trait]
    pub trait Execute: std::marker::Send + std::marker::Sync + 'static {
        async fn get_quote(
            &self,
            request: tonic::Request<super::GetQuoteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetQuoteResponse>,
            tonic::Status,
        >;
        async fn execute(
            &self,
            request: tonic::Request<super::ExecuteRequest>,
        ) -> std::result::Result<tonic::Response<super::ExecuteResponse>, tonic::Status>;
        async fn execute_status(
            &self,
            request: tonic::Request<super::ExecuteStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExecuteStatusResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the ExecuteStream method.
        type ExecuteStreamStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ExecuteStreamEvent, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn execute_stream(
            &self,
            request: tonic::Request<super::ExecuteStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::ExecuteStreamStream>,
            tonic::Status,
        >;
        async fn execute_result(
            &self,
            request: tonic::Request<super::ExecuteResultRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExecuteResultResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct ExecuteServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ExecuteServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ExecuteServer<T>
    where
        T: Execute,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/hellas.Execute/GetQuote" => {
                    #[allow(non_camel_case_types)]
                    struct GetQuoteSvc<T: Execute>(pub Arc<T>);
                    impl<T: Execute> tonic::server::UnaryService<super::GetQuoteRequest>
                    for GetQuoteSvc<T> {
                        type Response = super::GetQuoteResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetQuoteRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Execute>::get_quote(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetQuoteSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.Execute/Execute" => {
                    #[allow(non_camel_case_types)]
                    struct ExecuteSvc<T: Execute>(pub Arc<T>);
                    impl<T: Execute> tonic::server::UnaryService<super::ExecuteRequest>
                    for ExecuteSvc<T> {
                        type Response = super::ExecuteResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ExecuteRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Execute>::execute(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ExecuteSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.Execute/ExecuteStatus" => {
                    #[allow(non_camel_case_types)]
                    struct ExecuteStatusSvc<T: Execute>(pub Arc<T>);
                    impl<
                        T: Execute,
                    > tonic::server::UnaryService<super::ExecuteStatusRequest>
                    for ExecuteStatusSvc<T> {
                        type Response = super::ExecuteStatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ExecuteStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Execute>::execute_status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ExecuteStatusSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.Execute/ExecuteStream" => {
                    #[allow(non_camel_case_types)]
                    struct ExecuteStreamSvc<T: Execute>(pub Arc<T>);
                    impl<
                        T: Execute,
                    > tonic::server::ServerStreamingService<super::ExecuteStatusRequest>
                    for ExecuteStreamSvc<T> {
                        type Response = super::ExecuteStreamEvent;
                        type ResponseStream = T::ExecuteStreamStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ExecuteStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Execute>::execute_stream(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ExecuteStreamSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hellas.Execute/ExecuteResult" => {
                    #[allow(non_camel_case_types)]
                    struct ExecuteResultSvc<T: Execute>(pub Arc<T>);
                    impl<
                        T: Execute,
                    > tonic::server::UnaryService<super::ExecuteResultRequest>
                    for ExecuteResultSvc<T> {
                        type Response = super::ExecuteResultResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ExecuteResultRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Execute>::execute_result(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ExecuteResultSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ExecuteServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "hellas.Execute";
    impl<T> tonic::server::NamedService for ExecuteServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
