[package]
name = "hellas-executor"
description = "Executor for the Hellas node"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
hellas-rpc = { path = "../rpc", features = ["server"] }
tokio = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
