[package]
name = "hellas-executor"
description = "Executor for the Hellas node"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[features]
default = ["evaluate"]
evaluate = [
    "dep:catena-runner",
    "dep:commonware-runtime",
]

[dependencies]
anyhow = "1"
async-trait = "0.1"
catena-runner = { workspace = true, default-features = false, features = ["fetch", "runtime"], optional = true }
commonware-runtime = { workspace = true, optional = true }
futures-core = "0.3"
futures-util = "0.3"
hellas-chain = { workspace = true, features = ["client"] }
hellas-kernel = { workspace = true, features = ["secp256k1"] }
hellas-rpc = { workspace = true, features = [
    "execute",
    "evaluate",
    "fetch",
    "courtesy",
    "work",
] }
hellas-wire = { workspace = true }
prometheus-client = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = "0.7"
tracing = { workspace = true }
uuid = { version = "1", features = ["v4"] }
zeroize = "1"
