use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // Capture git rev for version info.
    // Try git from this crate's own repo first (correct for cross-workspace path deps),
    // then fall back to GIT_REV env var (set by nix where git is unavailable).
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let rev = std::process::Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .current_dir(&manifest_dir)
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string());
    if let Some(rev) = rev {
        println!("cargo:rustc-env=GIT_REV={rev}");
    } else if let Ok(rev) = std::env::var("GIT_REV") {
        println!("cargo:rustc-env=GIT_REV={rev}");
    }
    println!("cargo:rerun-if-changed=../../.git/HEAD");
    println!("cargo:rerun-if-changed=../../.git/refs");

    generate_service_markers(Path::new(&manifest_dir));
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct RpcMethod {
    service: String,
    name: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct RpcService {
    package: String,
    name: String,
    methods: Vec<RpcMethod>,
}

fn generate_service_markers(manifest_dir: &Path) {
    let proto_root = manifest_dir.join("../../proto/hellas");
    let mut protos = Vec::new();
    collect_proto_files(&proto_root, &mut protos);
    protos.sort();

    for proto in &protos {
        println!("cargo:rerun-if-changed={}", proto.display());
    }

    let services = protos
        .iter()
        .flat_map(|proto| parse_proto_services(proto))
        .collect::<Vec<_>>();
    let generated = render_service_markers(&services);

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));
    fs::write(out_dir.join("service_markers.rs"), generated)
        .expect("failed to write generated service markers");
}

fn collect_proto_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_proto_files(&path, out);
        } else if path.extension().is_some_and(|ext| ext == "proto") {
            out.push(path);
        }
    }
}

fn parse_proto_services(path: &Path) -> Vec<RpcService> {
    let source = fs::read_to_string(path).expect("proto file should be readable");
    let mut package = String::new();
    let mut services = Vec::new();
    let mut current: Option<RpcService> = None;

    for raw_line in source.lines() {
        let line = raw_line
            .split_once("//")
            .map_or(raw_line, |(prefix, _)| prefix)
            .trim();
        if line.is_empty() {
            continue;
        }

        if let Some(rest) = line.strip_prefix("package ") {
            package = rest.trim_end_matches(';').trim().to_owned();
            continue;
        }

        if let Some(rest) = line.strip_prefix("service ") {
            let name = rest
                .split(|ch: char| ch == '{' || ch.is_whitespace())
                .find(|part| !part.is_empty())
                .expect("service name should be present")
                .to_owned();
            current = Some(RpcService {
                package: package.clone(),
                name,
                methods: Vec::new(),
            });
            continue;
        }

        if line.starts_with('}') {
            if let Some(service) = current.take() {
                services.push(service);
            }
            continue;
        }

        if let Some(service) = current.as_mut()
            && let Some(rest) = line.strip_prefix("rpc ")
        {
            let name = rest
                .split(|ch: char| ch == '(' || ch.is_whitespace())
                .find(|part| !part.is_empty())
                .expect("rpc method name should be present")
                .to_owned();
            service.methods.push(RpcMethod {
                service: service.name.clone(),
                name,
            });
        }
    }

    if let Some(service) = current {
        services.push(service);
    }

    services
}

fn render_service_markers(services: &[RpcService]) -> String {
    let mut output = String::from(
        "// @generated by crates/rpc/build.rs. Do not edit by hand.\n\n\
         use crate::peers::ServiceKey;\n\n",
    );

    for service in services {
        let service_ident = service_ident(&service.name);
        let service_name = format!("{}.{}", service.package, service.name);
        output.push_str(&format!(
            "pub struct {service_ident};\n\n\
             impl ServiceKey for {service_ident} {{\n\
                 const NAME: &'static str = \"{service_name}\";\n\
             }}\n\n\
             impl tonic::server::NamedService for {service_ident} {{\n\
                 const NAME: &'static str = <Self as ServiceKey>::NAME;\n\
             }}\n\n",
        ));
    }

    let method_counts = method_counts(services);
    output.push_str("pub mod methods {\n");
    output.push_str("    use crate::peers::MethodKey;\n");
    for service in services {
        output.push_str(&format!(
            "    use super::{};\n",
            service_ident(&service.name)
        ));
    }
    output.push('\n');

    for service in services {
        let service_ident = service_ident(&service.name);
        for method in &service.methods {
            let method_ident = method_ident(method, &method_counts);
            output.push_str(&format!(
                "    pub struct {method_ident};\n\n\
                     impl MethodKey for {method_ident} {{\n\
                         type Service = {service_ident};\n\
                         const NAME: &'static str = \"{}\";\n\
                     }}\n\n",
                method.name
            ));
        }
    }

    output.push_str("}\n");
    output
}

fn method_counts(services: &[RpcService]) -> HashMap<String, usize> {
    let mut counts = HashMap::new();
    for service in services {
        for method in &service.methods {
            *counts.entry(method.name.clone()).or_insert(0) += 1;
        }
    }
    counts
}

fn service_ident(service: &str) -> String {
    format!("{service}Service")
}

fn method_ident(method: &RpcMethod, method_counts: &HashMap<String, usize>) -> String {
    if method_counts.get(&method.name).copied().unwrap_or(0) > 1 {
        format!("{}{}", method.service, method.name)
    } else {
        method.name.clone()
    }
}
