[package]
name = "hellas-jobs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
hellas-xet = { workspace = true, features = ["chunking"] }
trait-variant = "0.1"

[dev-dependencies]
futures.workspace = true
